#!/usr/bin/env bash
# Make small, fast-loading WebP previews of every image (PNG/JPG/WebP) and PDF,
# and write their details (preview size, file size, page count) to
# _data/media.yml, which the templates read.
#
#   scripts/thumbnails.sh          # (re)make previews that are missing or out of date
#   scripts/thumbnails.sh --force  # remake all of them
#
# Previews go in assets/thumbs/, mirroring the original's path:
#   ariel/gallery/decode.png  ->  assets/thumbs/ariel/gallery/decode.webp
# Pages never load the originals; they are only fetched when someone clicks
# through to view or download them.
#
# Needs: brew install webp poppler
set -euo pipefail
cd "$(dirname "$0")/.."

WIDTH=800   # default preview width in px: sharp at ~400px on a retina screen
OUT=assets/thumbs
DATA=_data/media.yml
FORCE=${1:-}

# A few images are shown bigger than usual and need a wider preview.
width_for() {
  case "$1" in
    ccc/ClimateChangeCommittee.png) echo 1400 ;;  # full-width banner on /ccc/
    qsl/qsl.webp) echo 2200 ;;                    # fills the screen on /qsl/
    *) echo "$WIDTH" ;;
  esac
}

for tool in cwebp webpinfo pdftoppm pdfinfo; do
  command -v "$tool" >/dev/null || { echo "Missing $tool: run 'brew install webp poppler'" >&2; exit 1; }
done

# Phone photos are often stored sideways, with a note in the EXIF data saying
# which way up to show them. cwebp ignores that note, so read it here and
# prints how many degrees clockwise to turn the picture (0, 90, 180 or 270).
exif_rotation() {
  python3 - "$1" 2>/dev/null <<'PY' || echo 0
import struct, sys
d = open(sys.argv[1], "rb").read()
i = 2
while d[:2] == b"\xff\xd8" and i + 4 <= len(d) and d[i] == 0xFF and d[i + 1] != 0xDA:
    size = struct.unpack(">H", d[i + 2:i + 4])[0]
    if d[i + 1] == 0xE1 and d[i + 4:i + 10] == b"Exif\0\0":
        t = d[i + 10:i + 2 + size]
        e = "<" if t[:2] == b"II" else ">"
        ifd = struct.unpack(e + "I", t[4:8])[0]
        for k in range(struct.unpack(e + "H", t[ifd:ifd + 2])[0]):
            p = ifd + 2 + 12 * k
            if struct.unpack(e + "H", t[p:p + 2])[0] == 0x112:  # Orientation
                print({3: 180, 6: 90, 8: 270}.get(struct.unpack(e + "H", t[p + 8:p + 10])[0], 0))
                sys.exit()
    i += 2 + size
print(0)
PY
}

human_size() {
  awk -v b="$1" 'BEGIN {
    if (b >= 1048576) printf "%.1f MB", b / 1048576;
    else if (b >= 1024) printf "%.0f KB", b / 1024;
    else printf "%d bytes", b }'
}

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
touch "$tmp/expected"

{
  echo "# GENERATED by scripts/thumbnails.sh - do not edit by hand, just re-run it."
  echo "# One entry per image/PDF/download: preview (thumb) path and size, file size, pages."
} > "$tmp/media.yml"

# Every tracked or new (not ignored) file we might show or offer for download.
git ls-files -co --exclude-standard \
  | grep -Ei '\.(png|jpe?g|webp|pdf|stl|otf|ttf|zip)$' \
  | grep -Ev "^($OUT|_site|vendor)/" \
  | sort \
  | while IFS= read -r src; do
      [ -f "$src" ] || continue
      ext=$(echo "${src##*.}" | tr '[:upper:]' '[:lower:]')
      bytes=$(wc -c < "$src" | tr -d ' ')
      {
        echo "\"/$src\":"
        echo "  size: $(human_size "$bytes")"
      } >> "$tmp/media.yml"

      case "$ext" in png|jpg|jpeg|webp|pdf) ;; *) continue ;; esac

      thumb="$OUT/${src%.*}.webp"
      echo "$thumb" >> "$tmp/expected"
      if [ "$FORCE" = "--force" ] || [ ! -f "$thumb" ] || [ "$src" -nt "$thumb" ]; then
        echo "preview: $src"
        mkdir -p "$(dirname "$thumb")"
        w=$(width_for "$src")
        if [ "$ext" = pdf ]; then
          pdftoppm -f 1 -l 1 -singlefile -png -scale-to-x "$w" -scale-to-y -1 "$src" "$tmp/page"
          cwebp -quiet -q 80 "$tmp/page.png" -o "$tmp/thumb.webp"
        else
          img=$src
          turn=0
          case "$ext" in jpg|jpeg) turn=$(exif_rotation "$src") ;; esac
          if [ "$turn" != 0 ]; then
            sips -r "$turn" -s format png "$src" --out "$tmp/turned.png" >/dev/null
            img=$tmp/turned.png
          fi
          cwebp -quiet -q 80 -resize "$w" 0 -resize_mode down_only "$img" -o "$tmp/thumb.webp"
        fi
        # Swap the finished file in at once, so a running serve.sh never
        # copies a half-written preview.
        mv "$tmp/thumb.webp" "$thumb"
      fi

      read -r tw th < <(webpinfo "$thumb" | awk '/Width:/ {w=$2} /Height:/ {h=$2} END {print w, h}')
      {
        echo "  thumb: /$thumb"
        echo "  width: $tw"
        echo "  height: $th"
      } >> "$tmp/media.yml"
      if [ "$ext" = pdf ]; then
        echo "  pages: $(pdfinfo "$src" | awk '/^Pages:/ {print $2}')" >> "$tmp/media.yml"
      fi
    done

# Remove previews whose original has been deleted or renamed.
if [ -d "$OUT" ]; then
  find "$OUT" -type f -name '*.webp' | sort | comm -23 - <(sort "$tmp/expected") | while IFS= read -r stale; do
    echo "removing stale preview: $stale"
    rm "$stale"
  done
  find "$OUT" -type d -empty -delete
fi

mv "$tmp/media.yml" "$DATA"
echo "wrote $DATA"
